# Generated by Django 5.2.8 on 2025-11-27 00:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plato',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('categoria', models.CharField(choices=[('ENTRADA', 'Entrada'), ('PRINCIPAL', 'Plato Fuerte'), ('POSTRE', 'Postre'), ('BEBIDA', 'Bebida'), ('OTRO', 'Otro')], default='PRINCIPAL', max_length=50)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('disponible', models.BooleanField(default=True)),
                ('tiempo_preparacion_min', models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('calorias', models.PositiveBigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('es_vegetariano', models.BooleanField(default=False)),
                ('nivel_picante', models.IntegerField(choices=[(0, 'No Picante'), (1, 'Suave'), (2, 'Medio'), (3, 'Alto'), (4, 'Extremo')], default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)])),
            ],
        ),
    ]
