# Generated by Django 5.2.8 on 2025-11-26 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Código del Plato')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(verbose_name='Descripción detallada')),
                ('categoria', models.CharField(max_length=50, verbose_name='Categoría (Ej: Entrada, Principal, Postre)')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Precio (€)')),
                ('disponible', models.BooleanField(default=True, verbose_name='¿Está disponible hoy?')),
                ('tiempo_preparacion_min', models.IntegerField(verbose_name='Tiempo de preparación (min)')),
                ('calorias', models.IntegerField(blank=True, null=True, verbose_name='Calorías estimadas')),
                ('es_vegetariano', models.BooleanField(default=False, verbose_name='¿Es vegetariano?')),
                ('nivel_picante', models.IntegerField(default=1, verbose_name='Nivel de Picante')),
            ],
            options={
                'verbose_name': 'Plato',
                'verbose_name_plural': 'Platos',
                'ordering': ['nombre'],
            },
        ),
    ]
